# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Project Aika

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pip-tools flake8 pytest pytest-cov
#        grep -v "^-e\|^\ \|^#" requirements.txt | xargs python -m pip install
        python -m pip install -e ./libs/utilities
        python -m pip install -e ./libs/time
        python -m pip install -e ./libs/ml
        python -m pip install -e ./libs/datagraph
        python -m pip install -e ./libs/putki
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./libs/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./libs/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
